name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
      - '*.js'
      - '*.py'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Check if version changed
        id: version-check
        run: |
          PUBLISHED_VERSION=$(npm view jupyter-markdown-mcp version 2>/dev/null || echo "0.0.0")
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          echo "published=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT
          echo "local=$LOCAL_VERSION" >> $GITHUB_OUTPUT
          if [ "$PUBLISHED_VERSION" != "$LOCAL_VERSION" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Publish to npm
        if: steps.version-check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create Release
        if: steps.version-check.outputs.changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version-check.outputs.local }}
          release_name: Release v${{ steps.version-check.outputs.local }}
          body: |
            ## Changes in v${{ steps.version-check.outputs.local }}
            
            - Renamed package from notebook-convert-mcp to jupyter-markdown-mcp
            - Perfect cell preservation with boundary markers
            - Improved round-trip conversion fidelity
            
            ### Installation
            ```bash
            npx -y jupyter-markdown-mcp@latest install
            ```
            
            ### Usage with Claude Code CLI
            ```bash
            claude mcp add jupyter-markdown-mcp -- npx -y jupyter-markdown-mcp@latest
            ```
          draft: false
          prerelease: false